const MILLISECONDS_IN_ONE_SECOND = 1000;
const MILLISECONDS_IN_ONE_MINUTE = MILLISECONDS_IN_ONE_SECOND * 60;
const MILLISECONDS_IN_ONE_HOUR = MILLISECONDS_IN_ONE_MINUTE * 60;
const MILLISECONDS_IN_ONE_DAY = MILLISECONDS_IN_ONE_HOUR * 24;
const MILLISECONDS_IN_ONE_WEEK = MILLISECONDS_IN_ONE_DAY * 7;


module.exports = {
  MILLISECONDS_IN_ONE_SECOND,
  MILLISECONDS_IN_ONE_MINUTE,
  MILLISECONDS_IN_ONE_HOUR,
  MILLISECONDS_IN_ONE_DAY,
  MILLISECONDS_IN_ONE_WEEK,
};
